---
title: "ETC5513 Assignment4 Group7"
author:
- familyname: xxxxx
  othernames: xxxxx
  address: Monash University
  correspondingauthor: true
- familyname: xxx
  othernames: xxx
  address: Monash University
- familyname: xxx
  othernames: xxx
  address: Monash University
department: Department of\newline Econometrics &\newline Business Statistics
organization: Acme Corporation
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  MonashEBSTemplates::report:
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE, messages=FALSE, warning=FALSE)
# Make sure you have the latest versions of rmarkdown and bookdown installed
library(ggplot2)
```


# Introduction

# Analysis

\section*{body 1}

\section*{body 2}

\section*{Crime analysis by State and Territory}

```{r library}
library(tidyverse)
library(readxl)
library(lubridate)
```

```{r nsw-cleaning}
nsw <- read_excel(here::here("data/2.+offenders,+states+and+territories.xls"), sheet = 3, range = "A6:L39")
```

```{r nsw-cleaning1}
nsw <- nsw %>% 
  dplyr::filter(!is.na(`Principal offence`))

nsw <- nsw[-c(16),] 

```

```{r nsw-cleaning2}
nsw <- nsw %>% 
  dplyr::filter(!is.na(`Principal offence`)) %>%
  mutate(state = rep("NSW", 30))

nsw$`2008–09` = as.double(nsw$`2008–09`)

nsw1 <- nsw %>% 
  pivot_longer(cols = `2008–09`:`2018–19`,
               names_to = "Year", 
               values_to = "cases") %>%
   mutate(Year = year(as.Date(Year, "%Y")))
```


```{r}
vic <- read_excel(here::here("data/2.+offenders,+states+and+territories.xls"), sheet = 4, range = "A6:L39")
```

```{r vic-cleaning1}
vic <- vic %>% 
  dplyr::filter(!is.na(`Principal offence`))

vic <- vic[-c(16),] 

```

```{r vic-cleaning2}
vic <- vic %>% 
  dplyr::filter(!is.na(`Principal offence`)) %>%
  mutate(state = rep("VIC", 30))

vic$`2008–09` = as.double(vic$`2008–09`)

vic1 <- vic %>% 
  pivot_longer(cols = `2008–09`:`2018–19`,
               names_to = "Year", 
               values_to = "cases") %>%
   mutate(Year = year(as.Date(Year, "%Y")))
```



```{r qld-cleaning}
qld <- read_excel(here::here("data/2.+offenders,+states+and+territories.xls"), sheet = 5, range = "A6:L39")
```

```{r vic-cleaning1}
qld <- qld %>% 
  dplyr::filter(!is.na(`Principal offence`))

qld <- qld[-c(16),] 

```


```{r qld-cleaning2}
qld <- qld %>% 
  dplyr::filter(!is.na(`Principal offence`)) %>%
  mutate(state = rep("QLD", 30))

qld$`2008–09` = as.double(qld$`2008–09`)

qld1 <- qld %>% 
  pivot_longer(cols = `2008–09`:`2018–19`,
               names_to = "Year", 
               values_to = "cases") %>%
   mutate(Year = year(as.Date(Year, "%Y")))
```



```{r}
sa <- read_excel(here::here("data/2.+offenders,+states+and+territories.xls"), sheet = 6, range = "A6:L39")
```

```{r sa-cleaning1}
sa <- sa %>% 
  dplyr::filter(!is.na(`Principal offence`))

sa <- sa[-c(16),] 

```

```{r sa-cleaning2}
sa <- sa %>% 
  dplyr::filter(!is.na(`Principal offence`)) %>%
  mutate(state = rep("SA", 30))

sa$`2008–09` = as.double(sa$`2008–09`)

sa1 <- sa %>% 
  pivot_longer(cols = `2008–09`:`2018–19`,
               names_to = "Year", 
               values_to = "cases") %>%
   mutate(Year = year(as.Date(Year, "%Y")))
```



```{r}
wa <- read_excel(here::here("data/2.+offenders,+states+and+territories.xls"), sheet = 7, range = "A6:L39")
```

```{r wa-cleaning1}
wa <- wa %>% 
  dplyr::filter(!is.na(`Principal offence`))

wa <- wa[-c(16),] 

```

```{r wa-cleaning2}
wa <- wa %>% 
  dplyr::filter(!is.na(`Principal offence`)) %>%
  mutate(state = rep("WA", 30))

wa$`2008–09` = as.double(wa$`2008–09`)

wa1 <- wa %>% 
  pivot_longer(cols = `2008–09`:`2018–19`,
               names_to = "Year", 
               values_to = "cases") %>%
   mutate(Year = year(as.Date(Year, "%Y")))
```


```{r}
tas <- read_excel(here::here("data/2.+offenders,+states+and+territories.xls"), sheet = 8, range = "A6:L39")
```

```{r tas-cleaning1}
tas <- tas %>% 
  dplyr::filter(!is.na(`Principal offence`))

tas <- tas[-c(16),] 

```

```{r tas-cleaning2}
tas <- tas %>% 
  dplyr::filter(!is.na(`Principal offence`)) %>%
  mutate(state = rep("TAS", 30))

tas$`2008–09` = as.double(tas$`2008–09`)

tas1 <- tas %>% 
  pivot_longer(cols = `2008–09`:`2018–19`,
               names_to = "Year", 
               values_to = "cases") %>%
   mutate(Year = year(as.Date(Year, "%Y")))
```

```{r}
nt <- read_excel(here::here("data/2.+offenders,+states+and+territories.xls"), sheet = 9, range = "A6:L39")
```

```{r nt-cleaning1}
nt <- nt %>% 
  dplyr::filter(!is.na(`Principal offence`))

nt <- nt[-c(16),] 

```

```{r tas-cleaning2}
nt <- nt %>% 
  dplyr::filter(!is.na(`Principal offence`)) %>%
  mutate(state = rep("NT", 30))

nt$`2008–09` = as.double(nt$`2008–09`)

nt1 <- nt %>% 
  pivot_longer(cols = `2008–09`:`2018–19`,
               names_to = "Year", 
               values_to = "cases") %>%
   mutate(Year = year(as.Date(Year, "%Y")))
```

```{r}
act <- read_excel(here::here("data/2.+offenders,+states+and+territories.xls"), sheet = 10, range = "A6:L39")
```

```{r act-cleaning1}
act <- act %>% 
  dplyr::filter(!is.na(`Principal offence`))

act <- act[-c(16),] 

```

```{r tas-cleaning2}
act <- act %>% 
  dplyr::filter(!is.na(`Principal offence`)) %>%
  mutate(state = rep("ACT", 30))

act$`2008–09` = as.double(act$`2008–09`)

act1 <- act %>% 
  pivot_longer(cols = `2008–09`:`2018–19`,
               names_to = "Year", 
               values_to = "cases") %>%
   mutate(Year = year(as.Date(Year, "%Y")))
```

```{r join1}
join1 <- full_join(
  nsw1,
  vic1,
  by = c("Principal offence" = "Principal offence",
         "state" = "state",
         "Year" = "Year",
         "cases" = "cases"))

join2 <- full_join(
  qld1,
  sa1,
  by = c("Principal offence" = "Principal offence",
         "state" = "state",
         "Year" = "Year",
         "cases" = "cases"))

join3 <- full_join(
  wa1,
  tas1,
  by = c("Principal offence" = "Principal offence",
         "state" = "state",
         "Year" = "Year",
         "cases" = "cases"))

join4 <- full_join(
  nt1,
  act1,
  by = c("Principal offence" = "Principal offence",
         "state" = "state",
         "Year" = "Year",
         "cases" = "cases"))

join5 <- full_join(
  join1,
  join2,
  by = c("Principal offence" = "Principal offence",
         "state" = "state",
         "Year" = "Year",
         "cases" = "cases"))

join6 <- full_join(
  join3,
  join4,
  by = c("Principal offence" = "Principal offence",
         "state" = "state",
         "Year" = "Year",
         "cases" = "cases"))

state_crime <- full_join(
  join5,
  join6,
  by = c("Principal offence" = "Principal offence",
         "state" = "state",
         "Year" = "Year",
         "cases" = "cases"))
state_crime$Year = as.factor(state_crime$Year)
```

```{r}
graph1 <- state_crime %>%
  group_by(state) %>%
  ggplot(aes(state, cases,
             colour = state,
             fill = state)) +
  geom_col()
graph1
```
\ The figure above demonstrates high crime cases recorded by NSW, QLD, SA, VIC and WA. However, the high number of crime cases recorded in these states may due to its high population compared to other states/territories like ACT, NT and TAS.

# Conclusion

# Reference